name: LEGO DNS Certificates
version: "1.0.0"
slug: lego-dns
description: Automate Let's Encrypt certificate issuance with lego using DNS challenges.
url: https://github.com/deg0nz/ha-lego
hassio_api: true
hassio_role: manager
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
boot: auto
init: false
map:
  - ssl:rw
options:
  email: ""
  domains: []
  key_type: rsa2048
  cron_schedule: "0 3 * * *"
  renew_days: 30
  lego_path: /data/lego
  staging: false
  dns_provider: inwx
  dns_resolvers: ""
  dns_provider_env: []
  restart_addon_slug: ""
  force_initial_request: false
schema:
  email: str
  domains:
    - str
  key_type: list(rsa2048|rsa4096|ec256|ec384)
  cron_schedule: str
  renew_days: int(1,)
  lego_path: str
  staging: bool
  dns_provider: str
  dns_resolvers: str
  dns_provider_env:
    - str
  restart_addon_slug: str?
  force_initial_request: bool
